travis:
  secure:
    BINSTAR_TOKEN: SUYK75dy3nZnnmhPLvwKMzRP6/fd32uTzKsbxMy1D1F1r5NUEta2J4alQ6Yo0Zwevd4htgtOltSnkEpYBQP1SvggTbQWO8xTjCPi5Hz/8hYpwk+9/CvYn5RQCoGTwi2ktUT19SA1khdY6lxr5IDbgxSF5RoEMdRs4ZCsuP4cbothgY4oEQJX40R1adIo5oh8gLpgoImn+ZxB+jl3khSXJPaeca0tn/l3Mg5KhCxwpF7suvaiclm+35FGhS2QewcXMa/t+DpTmoL3oNFQFseo1TqIeyeJ/rokCRiHXKusgT4sX00/Qnh2QUz6yQYGBe7KuB8aLIWxAFihI+qSMHFf4qbHGpBj3D0q+/qeD6H5BH1qy+pPQWS2doVu0aKcB++Q6GS/Y7FYqZkAly+SGrxw7ydTBXYxUGONHhT+ffhMCuQoVq9i4W28L1tlf+RkHfRxg2cZBBk+uQJuAZTqYZt1bWiEm7MzOZO7DYEtQlA961nhxQsExeuM2zcQO13vrsNgXEeIPcpdBQO7j8EG1D+tQ5dF1xwrubSdQaHsB8fPRNTAtNXGtLhCJJllPq9XIQCs2izTZ5HlhD7QK/3PJk32SL3dHSgNCbOdovIMgHJj40NAPZ+b3kvyPn1B3HxkwgHofNI41ID+W3sQFOT51ZjtDV8MPLUQBYQm+c/lbnxrS8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
